{% set name = "sphinxcontrib-apidoc" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe59d15882472aa93c2737afbdea6bedb34ce35cbd34aa4947909f5df1500aad

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - pbr
  run:
    - pbr
    - python

test:
  imports:
    - sphinxcontrib

about:
  home: https://pypi.org/project/sphinxcontrib-apidoc/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A Sphinx extension for running sphinx-apidoc on each build.'
  description: sphinx-apidoc is a tool for automatic generation of Sphinx sources that, using the autodoc extension, documents a whole package in the style of other automatic API documentation tools. sphinx-apidoc does not actually build documentation - rather it simply generates it. As a result, it must be run before sphinx-build.
  doc_url: https://pypi.org/project/sphinxcontrib-apidoc/
  dev_url: https://github.com/sphinx-contrib/apidoc

extra:
  recipe-maintainers:
    - CurtLH
