{% set name = "sphinxcontrib-apidoc" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 329b9810d66988f48e127a6bd18cc8efbbd1cd20b8deb4691a35738af49ad88d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - pbr
  run:
    - pbr
    - python

test:
  imports:
    - sphinxcontrib

about:
  home: https://pypi.org/project/sphinxcontrib-apidoc/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A Sphinx extension for running sphinx-apidoc on each build.'
  description: sphinx-apidoc is a tool for automatic generation of Sphinx sources that, using the autodoc extension, documents a whole package in the style of other automatic API documentation tools. sphinx-apidoc does not actually build documentation - rather it simply generates it. As a result, it must be run before sphinx-build.
  doc_url: https://pypi.org/project/sphinxcontrib-apidoc/
  dev_url: https://github.com/sphinx-contrib/apidoc

extra:
  recipe-maintainers:
    - CurtLH
